### ISSUE TITLE
Feature: Midi file seeking

### ISSUE THREAD

**Issue by sevonj** [sinshu/rustysynth#21]
Hi, I just built a basic midi player using RustySynth: https://github.com/sevonj/sfontplayer

It seems that MidiSequencer doesn't support changing the position in the file. Would seeking be a realistic feature to add? Thanks.

**Comment by sinshu** [comment]
I'm glad if this library has been of any help 😊

Regarding seeking in the MidiSequencer, there are various ways to implement MIDI file seeking, each with its own advantages and disadvantages. It's difficult to create a general-purpose seeking algorithm that can handle different requirements. Therefore, RustySynth does not provide a seeking feature. My opinion is that if users need seeking functionality, they should implement their own sequencer.

**Comment by sevonj** [comment]
In that case I'll look into implementing it myself. Thanks!
