### ISSUE TITLE
Use more informative error types

### ISSUE THREAD

**Issue by lunabunn** [sinshu/rustysynth#3]
It would be much easier for downstream crates to handle errors if they were returned as `enum`s rather than String errors in the form `Box<dyn Error>`. Not only are the current errors impossible to match on, they are also incompatible with error handling solutions such as `anyhow`.

If this change would be welcome, I would be willing to PR it?

**Comment by sinshu** [comment]
Since I'm still new to Rust, PRs to make the code more idiomatic are welcome 😄

**Comment by sinshu** [comment]
I tried adding error types: #7
However, I'm not sure if this is natural from the perspective of Rust's conventions.

**Comment by sinshu** [comment]
I've reviewed some error-related docs, and it seems fine, so I'll merge it and close this issue.
