### ISSUE TITLE
No support for sf3

### ISSUE THREAD

**Issue by alters-mit** [sinshu/rustysynth#4]
I tried using ms_basic.sf3 from MuseScore. Everything loads correctly but most of the presets sounds like bad white noise.

I converted ms_basic.sf3 to an sf2 file using Polyphone. rustysynth handles ms_basic.sf2 correctly.

Possibly, this is because sf3 uses ogg vorbis samples.

**Comment by sinshu** [comment]
To keep the code simple, I will not support SF3. However, it may be necessary to ensure that SF3 loading fails with an error.

**Comment by sinshu** [comment]
Made it so that loading SoundFont3 causes a `SoundFontError::UnsupportedSampleFormat` error to occur: https://github.com/sinshu/rustysynth/commit/2b3e9153fecdf9a3dad8b6d4ed8308561d08aaa3
