### ISSUE TITLE
Skip bytes if the track end event ends before the chunk length

### ISSUE THREAD

**Issue by ArthurCose** [sinshu/rustysynth#8]
I have [this midi file](https://github.com/sinshu/rustysynth/files/11438449/Archive.zip) that ends the track chunk with multiple track end events:

![image](https://github.com/sinshu/rustysynth/assets/15239026/51dfcca6-4a84-442e-a749-c3caca956af9)

Currently, the MidiFile struct will see the track end and immediately attempt to process the next event as an MTrk header giving me an InvalidChunkType for "??/?". Tracking the number of bytes read and skipping excess bytes (the extra event) allows the file to be fully read + play.

I have a fork that wraps the reader to track bytes read for resolving how many bytes to skip, not sure if there's a better solution.

**Comment by sinshu** [comment]
Thanks for reporting the issue and for the pull request 😄 Your proposed fix looks good.
After merging this pull request, would you mind if I changed the naming convention of the part you created to my personal preference?

**Comment by ArthurCose** [comment]
I wouldn't mind, thank you

**Comment by sinshu** [comment]
I've released v1.1.1 which fixes this issue. Thanks for the PR 😄
